version: '2'
services:
  bookstack:
    image: solidnerd/bookstack:21.12.1
    environment:
    - DB_HOST=db.dev.service:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstackusr
    - DB_PASSWORD=bookstackpass
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
    - APP_URL=http://dev-bookstack.myoperator.dev
    - APP_ENV=development
    - GOOGLE_AUTO_REGISTER=true
    - GOOGLE_APP_ID=1067017166742-0ddf80gvahissspm4p62tenk4uelenfl.apps.googleusercontent.com
    - GOOGLE_APP_SECRET=PlKPzhAZNkvhBP43ckfX0_xH
    #volumes:
    #- ./data/public/uploads:/var/www/bookstack/public/uploads
    #- ./data/storage/uploads:/var/www/bookstack/storage/uploads
    ports:
    - "8080:8080"

